CODE_PUSH = "code_push"
CODE_ANALYSIS = "code_analysis"
TEST_RESULTS = "test_results"
BUILD_READY = "build_ready"
IAC_READY = "iac_ready"
DEPLOYMENT_TRIGGERED = "deployment_triggered"
OBSERVABILITY_ALERT = "observability_alert"
ROLLBACK_EVENT = "rollback_event"